[package]
name = "particle_transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.18", features = ["derive"]}
eframe = "0.18.0"
fastrand = "1.7.0"
num = "0.4.0"
